version: 2
defaults: &defaults
  docker:
    - image: 'circleci/node:latest'
jobs:
  build:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run:
          name: Run full build
          command: npm run build
      - run:
          name: Run integration Tests
          command: npm run test:integration
      - store_artifacts:
          path: coverage
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run:
          name: Publish package
          command: npm run semantic-release || true
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: main